apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
    - port: 8081          # Service port (inside cluster)
      targetPort: 80    # Container port (nginx inside pod)
      nodePort: 30071   # Fixed NodePort (mapped in your kind config)


# kubectl port-forward service/my-nginx-service 30008:80
# kubectl port-forward svc/nginx-service 8080:80
# http://localhost:8080


# kubectl port-forward pod/nginx-deployment-6d4cf56db6-abcde 30008:80

